<?php
require_once __DIR__.'/../config.php';require_role(['admin']);$error='';
$start=input('from',$_GET,date('Y-m-01'));$end=input('to',$_GET,date('Y-m-d'));
$validDate=static function(string $v):bool{$d=DateTimeImmutable::createFromFormat('!Y-m-d',$v);return $d&&$d->format('Y-m-d')===$v;};
if(!$validDate($start)||!$validDate($end)||$start>$end||(new DateTimeImmutable($start))->diff(new DateTimeImmutable($end))->days>731){$error='Chọn khoảng ngày hợp lệ, tối đa 2 năm. Đang hiển thị tháng hiện tại.';$start=date('Y-m-01');$end=date('Y-m-d');}
$until=(new DateTimeImmutable($end))->modify('+1 day')->format('Y-m-d');
$stats=query("SELECT COUNT(*) AS total,COALESCE(SUM(trang_thai='cho_xu_ly'),0) AS pending,COALESCE(SUM(trang_thai='da_huy'),0) AS cancelled FROM don_hang WHERE ngay_dat>=? AND ngay_dat<?",[$start,$until])->fetch();
$revenue=query("SELECT COALESCE(SUM(tong_tien),0) AS revenue,COUNT(*) AS completed FROM don_hang WHERE trang_thai='hoan_thanh' AND trang_thai_thanh_toan='da_thanh_toan' AND ngay_hoan_thanh>=? AND ngay_hoan_thanh<?",[$start,$until])->fetch();
$months=query("SELECT DATE_FORMAT(ngay_hoan_thanh,'%Y-%m') AS month,SUM(tong_tien) AS revenue FROM don_hang WHERE trang_thai='hoan_thanh' AND trang_thai_thanh_toan='da_thanh_toan' AND ngay_hoan_thanh>=? AND ngay_hoan_thanh<? GROUP BY DATE_FORMAT(ngay_hoan_thanh,'%Y-%m') ORDER BY month",[$start,$until])->fetchAll();
$map=array_column($months,'revenue','month');$bars=[];
for($m=(new DateTimeImmutable($start))->modify('first day of this month');$m->format('Y-m')<=substr($end,0,7);$m=$m->modify('+1 month'))$bars[$m->format('m/Y')]=$map[$m->format('Y-m')]??'0.00';
$max=max(1,...array_map('cents',array_values($bars)));
$top=query("SELECT sp.id_san_pham,sp.ten_san_pham,SUM(ct.so_luong) AS quantity,SUM(ct.thanh_tien) AS revenue FROM chi_tiet_don_hang ct JOIN don_hang dh ON dh.id_don_hang=ct.id_don_hang JOIN bien_the_san_pham bt ON bt.id_bien_the=ct.id_bien_the JOIN san_pham sp ON sp.id_san_pham=bt.id_san_pham WHERE dh.trang_thai='hoan_thanh' AND dh.trang_thai_thanh_toan='da_thanh_toan' AND dh.ngay_hoan_thanh>=? AND dh.ngay_hoan_thanh<? GROUP BY sp.id_san_pham,sp.ten_san_pham ORDER BY quantity DESC,revenue DESC LIMIT 5",[$start,$until])->fetchAll();
$low=query('SELECT sp.ten_san_pham,sp.id_san_pham,bt.so_luong_ton,kt.ten_kich_thuoc,ms.ten_mau_sac FROM bien_the_san_pham bt JOIN san_pham sp ON sp.id_san_pham=bt.id_san_pham JOIN kich_thuoc kt ON kt.id_kich_thuoc=bt.id_kich_thuoc JOIN mau_sac ms ON ms.id_mau_sac=bt.id_mau_sac WHERE sp.trang_thai=1 AND bt.so_luong_ton<=5 ORDER BY bt.so_luong_ton,sp.id_san_pham LIMIT 10')->fetchAll();
$page_title='Báo cáo kinh doanh';require __DIR__.'/../header.php';
?>
<main id="main" class="container section"><div class="page-heading"><div><p class="eyebrow">ADMIN / OVERVIEW</p><h1>Báo cáo kinh doanh</h1></div><a class="btn" href="<?=e(url('orders/manage.php'))?>">Xử lý đơn hàng ↗</a></div>
<?php if($error):?><div class="alert alert-error"><?=e($error)?></div><?php endif;?>
<form class="toolbar" method="get"><div><label for="from">Từ ngày</label><input id="from" name="from" type="date" required value="<?=e($start)?>"></div><div><label for="to">Đến ngày</label><input id="to" name="to" type="date" required value="<?=e($end)?>"></div><button class="btn">Xem báo cáo</button></form>
<div class="stats"><div class="stat"><p>Doanh thu đã hoàn thành</p><strong><?=money($revenue['revenue'])?></strong><small><?=$revenue['completed']?> đơn đã hoàn thành & thu tiền</small></div><div class="stat"><p>Đơn đặt trong kỳ</p><strong><?=$stats['total']?></strong><small>Theo ngày đặt hàng</small></div><div class="stat"><p>Đang chờ xử lý</p><strong><?=$stats['pending']?></strong><small>Trong các đơn đặt trong kỳ</small></div><div class="stat"><p>Đơn đã hủy</p><strong><?=$stats['cancelled']?></strong><small>Không tính vào doanh thu</small></div></div>
<div class="dashboard-grid"><section class="panel"><h2>Doanh thu theo tháng</h2><p class="help">Theo ngày hoàn thành trong khoảng đã chọn; chỉ tính đơn đã nhận đủ tiền.</p><?php foreach($bars as $label=>$amount):?><div class="bar-row"><span><?=e($label)?></span><div class="bar-track"><div class="bar-fill" style="width:<?=round(cents($amount)/$max*100,2)?>%"></div></div><strong><?=money($amount)?></strong></div><?php endforeach;?></section>
<section class="panel"><h2>Sản phẩm bán chạy</h2><?php if(!$top):?><p class="muted">Chưa có đơn hoàn thành trong khoảng này.</p><?php endif;?><?php foreach($top as $i=>$p):?><div class="summary-line"><div><strong><?=($i+1).'. '.e($p['ten_san_pham'])?></strong><small><?=$p['quantity']?> sản phẩm đã bán</small></div><span class="nowrap"><?=money($p['revenue'])?></span></div><?php endforeach;?></section></div>
<section class="panel section-gap"><h2>Tồn kho cần chú ý</h2><p class="help">Các biến thể hiện còn không quá 5 sản phẩm; không phụ thuộc bộ lọc ngày.</p>
<?php if(!$low):?><p class="muted">Chưa có sản phẩm sắp hết hàng.</p><?php else:?><div class="table-wrap section-gap"><table><thead><tr><th>Sản phẩm</th><th>Size / màu</th><th>Còn lại</th><th></th></tr></thead><tbody><?php foreach($low as $p):?><tr><td><?=e($p['ten_san_pham'])?></td><td><?=e($p['ten_kich_thuoc'].' / '.$p['ten_mau_sac'])?></td><td><?=$p['so_luong_ton']?></td><td><a class="underlined" href="<?=e(url('products/edit.php?id='.$p['id_san_pham']))?>">Cập nhật kho</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section></main>
<?php require __DIR__.'/../footer.php';?>
